### PR TITLE
#25 Feature: Support multiple languages

### PR DESCRIPTION
**Pull request by Salim-54**
### What does this PR do?
- Support multiple languages
### Description of Task to be completed?

As a user, I want to be able to change the site language, so that the site contents get presented in the language I selected. 

- Users should be able to change/select a language of their choice.
- The site contents are presented in the newly set language.
- At least, two languages are supported.

### How should this be manually tested?
`Clone the repo`

`checkout` to branch `ft-multiple-languages-25`

pull the changes by `git pull`

install all packages by `running npm install`

start the app by running `npm run start`

### Any background context you want to provide?
N/A

### What are the relevant pivotal tracker stories?
[[Trello Board](https://trello.com/c/0CqEA90T/25-support-multiple-languages)]

### CODE REVIEW

**Review by tysepa — APPROVED** [review]

**Review by Xldivin — APPROVED** [review]

**Review by PrinceNiyonshuti — APPROVED** [review]
Looks Good

**Review by thepatrickniyo — CHANGES_REQUESTED** [review]
Try resolving the conflicts

**Review by benshyaka — APPROVED** [review]
looks good to me!

**Review by Hodal66 — APPROVED** [review]

**Comment by Salim-54** [comment]
> Try resolving the conflicts

It is now resolved

**Comment by benshyaka** [comment]
Feature: Support multiple languages: Card #25

**Pull request merged**
