### PR TITLE
#19 chore:setup docker

### PR DESCRIPTION
**Pull request by Xldivin**
#### What does this PR do?

- Implements setup the docker file for the frontend app(react-app)

#### Description of Task to be completed? 

- User can be able to run the app through the container

#### How should this be manually tested?

- Clone the repo

- checkout to branche ``develop``

- Run `npm install` to install modules

- Run ` docker run --publish 4000:4000 react` to run the app through the container

#### What are the relevant Pivotal Tracker/trello stories?

- https://trello.com/b/SK8fOo5R/elite-phantom-board

#### Screenshots (if appropriate)
- N/A

#### Questions:

- N/A

### CODE REVIEW

**Review by tysepa — COMMENTED** [review]
nice work

**Comment by Hodal66** [comment]
Yeah, nice work!!

**Review by Salim-54 — APPROVED** [review]

**Review by Hodal66 — APPROVED** [review]

**Comment by Xldivin** [comment]
[Setup Docker](https://trello.com/c/6CnMHtYC/19-setup-docker)

**Review by PrinceNiyonshuti — APPROVED** [review]
Looks good

**Review by thepatrickniyo — APPROVED** [review]

**Review by thepatrickniyo — COMMENTED** [review]
The work is good, but remember to resolve the conflicts in this branch

**Review by Niyonkuru1 — COMMENTED** [review]
The steps listed in the PR description for running docker did not work for me, may there is step missing. could you restate the steps to be followed?

**Comment by Niyonkuru1** [comment]
>

**Comment by Niyonkuru1** [comment]
I am sorry I closed this PR recently by accident.

**Pull request merged**
