### PR TITLE
Issue(fix): fix Heroku

### PR DESCRIPTION
**Pull request by rachelakimana**
**What does this PR do?**

 Fix an issue with running Heroku app 

*Description of Task to be completed?*

 Configure and connect repo to Heroku

*How should this be manually tested?*

Create Heroku app and connect to this repo

use issue-fix-heroku-1 branch to deploy

*What are the relevant Pivotal Tracker/trello stories?*

https://trello.com/b/SK8fOo5R/elite-phantom-board

Screenshots (if appropriate)
N/A
Questions:
N/A

### CODE REVIEW

**Review by Xldivin — APPROVED** [review]

**Review by thepatrickniyo — CHANGES_REQUESTED** [review]
Please rebase develop branch to solve the conflicts

**Review by PrinceNiyonshuti — APPROVED** [review]
Looks good to me, fix the issue mentioned by Patrick you will be good to go

**Review by Hodal66 — COMMENTED** [review]
GOOD Job!!

**Review by Xldivin — APPROVED** [review]

**Review by Hodal66 — APPROVED** [review]

**Comment by tysepa** [comment]
good fix

**Pull request merged**
