### PR TITLE
#27 Chore: configure heroku and codeclimate 

### PR DESCRIPTION
**Pull request by rachelakimana**
#### What does this PR do?
Configure Heroku and code climate

#### Description of Task to be completed?
Added yml for CI/CD and script for running coverage  on code climate and deploying to Heroku

#### How should this be manually tested?
clone this repo and cd into phantom-fe-elite folder, open it in your code editor.

test app bu running the following script:
npm install
npm run build
npm run test
npm run coverage
create an account to Heroku and deploy this branch
create an account to code climate and connect to this repo and choose this branch as a default branch

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
N/A
#### Screenshots (if appropriate)
N/A
#### Questions: N/A

### CODE REVIEW

**Review by tysepa — COMMENTED** [review]
so far so good

**Review by PrinceNiyonshuti — APPROVED** [review]
Looks good with me

**Review by Xldivin — APPROVED** [review]

**Review by thepatrickniyo — APPROVED** [review]
Looks good. Next time squash your commits into one.

**Review by thepatrickniyo — COMMENTED** [review]
Remove these conflicts to get the branch ready to merge

**Review by Hodal66 — APPROVED** [review]

**Comment by mukunzidd** [comment]
@rachelakimana please, update the title of your PR to match the convention.

**Comment by rachelakimana** [comment]
@PatrickNiyogitare28 @mukunzidd 
I have changed the title of the PR and resolved conflict.

**Pull request merged**
